name: Build Docker ECR Image
on:
  push:
    branches: [main]
    paths: [src/ecs_app/**]
  pull_request:
    branches: [main]
    paths: [src/ecs_app/**]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: cdk-lambda-ecs-repo
  VERSION: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/ecs_app
    steps:
      - uses: actions/checkout@v5

      - name: List files in ecs_app directory
        run: ls -la
