name: Build Docker ECR Image
on:
  push:
    branches: [main]
    paths: [src/ecs_app/**]
  pull_request:
    branches: [main]
    paths: [src/ecs_app/**]

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  IMAGE_NAME: cdk-lambda-ecs-repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3

      - name: Tag Docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}
            type=ref,event=pr
            type=sha

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./src/ecs_app
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
