name: Build Docker ECR Image
on:
  push:
    branches: [main]
    paths: [src/ecs_app/**]
  pull_request:
    branches: [main]
    paths: [src/ecs_app/**]

permissions:
  id-token: write
  contents: read

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  IMAGE_NAME: cdk-lambda-ecs-repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3

      - name: Tag Docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}
            type=ref,event=pr,prefix=pr-
            type=sha,prefix=sha-

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions_cdk_lambda_ecs
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ./src/ecs_app
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker

      - name: Display Docker image information
        run: |
          echo "Built Docker images:"
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          echo "Labels: ${{ steps.meta.outputs.labels }}"
          echo "Image digest: ${{ steps.build.outputs.digest }}"
          echo "Image ID: ${{ steps.build.outputs.imageid }}"
