name: Build Docker ECR Image
on:
  push:
    branches: [main]
    paths: [src/ecs_app/**]
  pull_request:
    branches: [main]
    paths: [src/ecs_app/**]

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  VERSION: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/ecs_app
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3

      - name: List files in ecs_app directory
        run: ls -la

      - name: Build Docker image
        run: make tag
